"""create meetings

Revision ID: 2e298145de06
Revises: bc0f5df9b7ec
Create Date: 2026-06-04 00:08:28.078399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e298145de06'
down_revision: Union[str, Sequence[str], None] = 'bc0f5df9b7ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('meeting_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meeting_link', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='scheduled', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_lead_id'), 'meetings', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetings_lead_id'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
