"""create leads

Revision ID: bc0f5df9b7ec
Revises: 600ec290add1
Create Date: 2026-06-03 23:28:05.351463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0f5df9b7ec'
down_revision: Union[str, Sequence[str], None] = '600ec290add1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_type', sa.String(length=120), nullable=True),
    sa.Column('platform', sa.String(length=120), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('budget', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='new', nullable=False),
    sa.Column('proposal', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_user_id'), 'leads', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_user_id'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
